
name: Node.js CI

on:
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install yarn
    - run: yarn build

    - name: Slack Failure Notification
      if: failure()
      run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
